server.port=8084
spring.application.name=collaboration-service

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/flowboard_collaboration?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=flowboard_super_secret_key_change_in_production_min_256_bits
app.jwt.expiry-ms=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html